on: 
  workflow_dispatch:
  issues:
    types: [opened]
env:
  nombre: 'Diego Antonio'
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo 'step 1'
      - name: Step 2
        run: echo 'step 2'
      - name: Step 3
        run: echo $nombre
  job2:
    name: Cowsays
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Ship ir
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: 'Hola hola hola'
          color: 'green'
